on:
  push:
jobs:
  compile:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: cachix/cachix-action@v12
      with:
        name: potsdam-pnp
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run nix build .#ippsample